### ISSUE TITLE
运行时错误

### ISSUE THREAD

**Issue by SnowFox4004** [xCipHanD/qqnt_backup#1]
有一个os.remove的调用会报错提示文件正在使用
![image](https://github.com/user-attachments/assets/a496f929-c03e-40a5-919e-b6888f815a31)
注释后也可以正常运行并读取但这个.db会出错
![image](https://github.com/user-attachments/assets/a76179cb-453a-4147-a2c8-433abdee9645)

**Comment by xCipHanD** [comment]
尝试一下修改`os.remove(encrypted_db)`为
```py
finally:
            if conn:
                conn.close()
            try:
                os.remove(encrypted_db)
            except OSError as e:
                print(f"删除文件 {encrypted_db} 失败，错误：{e}")
```

这个``gpro_v1-6_u_***.db``的加密方式与其他文件不同，暂时还不能解密。
