### ISSUE TITLE
在遇到过大的DB文件时，会报错 database disk image is malformed

### ISSUE THREAD

**Issue by BJ4501** [xCipHanD/qqnt_backup#3]
在对Db数据库进行解密时，前17个都可以正常解密，但是当解密到：
nt_msg.db(约4g) 与 group_msg_fts.db(约1g) 时解密失败，尝试打印Exception报了一个这样的错误：database disk image is malformed

查看输出文件夹，可以看到nt_msg.db与group_msg_fts.db文件都存在，但是导出的大小不正确，导出的内容也不完整。

有怀疑是cache不足导致的，尝试添加cursor.execute("PRAGMA cache_size = 8000;")依旧没有效果。

同时：
1.尝试重新复制出数据库文件并解密，规避文件问题，但依旧报错。并尝试登录qq，数据都可正常打开。
2.尝试登录一个新的账户，并复制数据库进行导出，nt_msg.db约几十KB，则可以完全正常导出。

所以怀疑是否是DB文件过大，导致导出异常的问题。因为看起来解密是成功了，但是在读取中出错。

想要咨询一下如果遇到这种DB文件过大的情况，应该如何处理。谢谢。

**Comment by xCipHanD** [comment]
你好，考虑可能是NTQQ进程正在读写该数据库导致导出的数据库文件不完整？

暂时没法复现你所说的情况，这边尝试解密约1G的nt_msg.db是成功的。（``pysqlcipher3==1.2.0``）

建议：尝试使用其他导出数据库的方式

**Comment by xCipHanD** [comment]
也可以尝试一下依据这个教程 [基础教程 - NTQQ 解密数据库.md](https://github.com/QQBackup/qq-win-db-key/blob/master/%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B%20-%20NTQQ%20%E8%A7%A3%E5%AF%86%E6%95%B0%E6%8D%AE%E5%BA%93.md) 对无法解密的数据库进行手动解密，可以使用``PRAGMA integrity_check;``语句对数据库进行完整性检查。

**Comment by BJ4501** [comment]
感谢作者的回复。
在尝试使用两部手机换机之后导出仍然有这个问题，怀疑是qq在升级nt版本时存在某些特殊的迁移逻辑导致db不完整。

解决方案：
使用官方qq迁移工具将全部数据导出到另外一个手机后，再进行数据库导出。此时可以正常导出。
如果有遇到类似问题的可以尝试一下这种方案。
